
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "FiraCode Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
